FROM kollaglue/centos-binary-manila-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-manila-share \
    && yum clean all

    




USER manila