FROM kollaglue/centos-binary-sahara-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-sahara-engine \
    && yum clean all

    




USER sahara