FROM kollaglue/centos-binary-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)



RUN yum -y install \
        iscsi-initiator-utils \
        targetcli \
        python-rtslib \
    && yum clean all



