FROM kollaglue/centos-binary-gnocchi-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-gnocchi-metricd \
    && yum clean all

    




USER gnocchi