FROM kollaglue/centos-binary-swift-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-swift-account \
    && yum clean all

    




USER swift