FROM kollaglue/centos-binary-manila-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    


COPY extend_start.sh /usr/local/bin/kolla_manila_extend_start
RUN chmod 755 /usr/local/bin/kolla_manila_extend_start



USER manila