FROM kollaglue/centos-binary-murano-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-murano-engine \
    && yum clean all

    




USER murano