FROM kollaglue/centos-binary-designate-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-designate-central \
    && yum clean all

    




USER designate