FROM kollaglue/centos-binary-ironic-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-ironic-conductor \
        qemu-img \
    && yum clean all

    




USER ironic