FROM kollaglue/centos-binary-trove-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-trove-conductor \
  && yum clean all

    




USER trove