FROM kollaglue/centos-binary-mistral-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-mistral-executor \
    && yum clean all

    




USER mistral