FROM kollaglue/centos-binary-aodh-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-aodh-listener \
  && yum clean all

    




USER aodh