FROM kollaglue/centos-binary-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


RUN yum -y install \
        git \
        iproute \
        openssl \
    && yum clean all



    

# TODO(Allen) Remove python-dogpile-cache after the requirement of
# python-ironicclient is fixed.
RUN yum -y install \
        avahi-libs \
        cups-libs \
        fontconfig \
        fontpackages-filesystem \
        freetype \
        initscripts \
        libjpeg-turbo \
        libpng \
        libtomcrypt \
        libtommath \
        libX11 \
        libX11-common \
        libXau \
        libxcb \
        libXext \
        libXi \
        libxslt \
        libyaml \
        MySQL-python \
        Percona-Server-shared-56 \
        pyOpenSSL \
        pyparsing \
        python2-cffi \
        python2-crypto \
        python2-cryptography \
        python2-debtcollector \
        python2-eventlet \
        python2-fasteners \
        python2-funcsigs \
        python2-futurist \
        python2-greenlet \
        python2-iso8601 \
        python2-msgpack \
        python2-oslo-concurrency \
        python2-oslo-config \
        python2-oslo-context \
        python2-oslo-db \
        python2-oslo-i18n \
        python2-oslo-log \
        python2-oslo-messaging \
        python2-oslo-middleware \
        python2-oslo-policy \
        python2-oslo-serialization \
        python2-oslo-service \
        python2-oslo-utils \
        python2-pika \
        python2-pika_pool \
        python2-positional \
        python2-pyasn1 \
        python2-PyMySQL \
        python-alembic \
        python-amqp \
        python-anyjson \
        python-barbicanclient \
        python-beaker \
        python-cachetools \
        python-ceilometerclient \
        python-cliff \
        python-cmd2 \
        python-congressclient \
        python-contextlib2 \
        python-dateutil \
        python-decorator \
        python-designateclient \
        python-dogpile-cache \
        python-editor \
        python-enum34 \
        python-extras \
        python-fixtures \
        python-futures \
        python-glanceclient \
        python-heatclient \
        python-httplib2 \
        python-idna \
        python-inotify \
        python-ipaddress \
        python-ironicclient \
        python-jsonpatch \
        python-jsonpointer \
        python-jsonschema \
        python-keyring \
        python-keystoneauth1 \
        python-keystoneclient \
        python-keystonemiddleware \
        python-kombu \
        python-linecache2 \
        python-lxml \
        python-magnumclient \
        python-mako \
        python-manilaclient \
        python-memcached \
        python-migrate \
        python-mimeparse \
        python-mistralclient \
        python-monotonic \
        python-muranoclient \
        python-netaddr \
        python-netifaces \
        python-neutronclient \
        python-novaclient \
        python-openstackclient \
        python-paste \
        python-paste-deploy \
        python-pbr \
        python-pip \
        python-ply \
        python-posix_ipc \
        python-prettytable \
        python-pycparser \
        python-PyMySQL \
        python-repoze-lru \
        python-requests \
        python-retrying \
        python-routes \
        python-saharaclient \
        python-simplejson \
        python-sqlalchemy \
        python-sqlparse \
        python-stevedore \
        python-swiftclient \
        python-tempita \
        python-testtools \
        python-traceback2 \
        python-troveclient \
        python-tuskarclient \
        python-unicodecsv \
        python-unittest2 \
        python-urllib3 \
        python-warlock \
        python-webob \
        python-wrapt \
        python-zaqarclient \
        PyYAML \
        systemd-sysv \
        sysvinit-tools \
        tcp_wrappers-libs \
    && yum clean all

    
