FROM kollaglue/centos-binary-heat-base:3.0.0
MAINTAINER Kolla Project (https://launchpad.net/kolla)


    

RUN yum -y install \
        openstack-heat-api-cfn \
    && yum clean all

    




USER heat